# Build stage
FROM node:20 as builder

WORKDIR /app
COPY package*.json ./
RUN npm install --loglevel verbose > npm_install.log  # Capture verbose logs
COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/npm_install.log /npm_install.log 

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
